'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Navbar } from '@/components/layout/Navbar';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Trophy, Star, Shield, ArrowUpRight, Award, Zap, Download, FileText, CheckCircle2 } from 'lucide-react';

export default function ProfileDashboard() {
  const [userData, setUserData] = useState<any>(null);
  const [isGeneratingCV, setIsGeneratingCV] = useState(false);
  const [cvData, setCvData] = useState<any>(null);

  // Radar Data
  const radarData = [
    { subject: 'Backend', A: 85, fullMark: 100 },
    { subject: 'Frontend', A: 65, fullMark: 100 },
    { subject: 'DevOps', A: 70, fullMark: 100 },
    { subject: 'Security', A: 60, fullMark: 100 },
    { subject: 'Database', A: 80, fullMark: 100 },
    { subject: 'System Design', A: 75, fullMark: 100 },
  ];

  useEffect(() => {
    const stored = localStorage.getItem('skillpath_onboarding_data');
    if (stored) {
      setUserData(JSON.parse(stored));
    } else {
      setUserData({ displayName: "Explorer User", pendidikan: "IT Mahasiswa" });
    }
  }, []);

  const handleGenerateCV = () => {
    setIsGeneratingCV(true);
    setTimeout(() => {
      setCvData({
        markdown: "# Resume\n\nGenerated by SkillPath AI based on verified projects and assessed skills.",
        recommendedRole: "Junior Full-Stack Engineer"
      });
      setIsGeneratingCV(false);
    }, 2500);
  };

  return (
    <div className="min-h-screen bg-[#0a0514] text-white pt-24 pb-12 overflow-x-hidden relative">
      <Navbar />

      {/* Decorative Blur Backgrounds */}
      <div className="fixed top-0 right-0 w-[50%] h-[50%] bg-[#5D1636]/20 rounded-full blur-[150px] pointer-events-none" />
      <div className="fixed bottom-0 left-[-20%] w-[50%] h-[50%] bg-indigo-600/10 rounded-full blur-[150px] pointer-events-none" />

      <main className="max-w-7xl mx-auto px-4 md:px-6 relative z-10 flex flex-col lg:flex-row gap-8">
        
        {/* Left Column (40%): Profile & Radar */}
        <div className="w-full lg:w-[40%] flex flex-col gap-6">
           
           {/* Profile Card */}
           <div className="glass p-8 rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl relative overflow-hidden group">
              <div className="absolute top-0 left-0 w-full h-32 bg-gradient-to-br from-[#5D1636] to-purple-900 opacity-60" />
              
              <div className="relative pt-12 flex flex-col items-center">
                 <div className="w-28 h-28 rounded-[2rem] bg-[#0a0514] border-4 border-[#0a0514] p-1 shadow-2xl relative mb-6 group-hover:scale-105 transition-transform duration-500">
                    <div className="w-full h-full rounded-[1.5rem] bg-gradient-to-br from-[#feb47b] to-[#ff7e5f] flex items-center justify-center text-4xl font-black text-[#5D1636]">
                       {userData?.displayName?.charAt(0).toUpperCase() || "U"}
                    </div>
                    <div className="absolute -bottom-2 -right-2 w-8 h-8 rounded-full bg-emerald-500 flex items-center justify-center border-2 border-[#0a0514] text-white">
                       <Shield size={16} />
                    </div>
                 </div>

                 <h1 className="text-3xl font-black mb-1">{userData?.displayName || "Explorer"}</h1>
                 <p className="text-[#feb47b] font-bold text-sm uppercase tracking-widest">{userData?.pendidikan || "Student"}</p>
                 
                 <div className="w-full h-px bg-white/10 my-8" />

                 <div className="flex w-full justify-between items-center text-center px-4">
                    <div>
                       <div className="text-2xl font-black flex items-center justify-center gap-1"><Star size={20} className="text-amber-400 fill-current" /> 1250</div>
                       <div className="text-[10px] text-white/50 uppercase tracking-widest mt-1">Total XP</div>
                    </div>
                    <div className="w-px h-10 bg-white/10" />
                    <div>
                       <div className="text-2xl font-black">Level 4</div>
                       <div className="text-[10px] text-white/50 uppercase tracking-widest mt-1">Cloud Novice</div>
                    </div>
                 </div>
              </div>
           </div>

           {/* Radar Chart (Custom SVG implementation for pure aesthetic control) */}
           <div className="glass p-8 rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl flex flex-col items-center relative">
              <h3 className="font-bold text-sm tracking-widest uppercase text-white/70 mb-8 self-start w-full border-b border-white/10 pb-4">Skill Radar</h3>
              
              <div className="relative w-64 h-64 mb-4">
                 <svg viewBox="0 0 100 100" className="w-full h-full drop-shadow-[0_0_20px_rgba(93,22,54,0.5)] overflow-visible">
                    {/* Grid Rings */}
                    <polygon points="50,10 90,30 90,70 50,90 10,70 10,30" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="1"/>
                    <polygon points="50,30 70,40 70,60 50,70 30,60 30,40" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="1"/>
                    <polygon points="50,50 60,55 60,65 50,70 40,65 40,55" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="1"/>
                    
                    {/* Axes */}
                    <line x1="50" y1="50" x2="50" y2="10" stroke="rgba(255,255,255,0.05)" strokeWidth="1"/>
                    <line x1="50" y1="50" x2="90" y2="30" stroke="rgba(255,255,255,0.05)" strokeWidth="1"/>
                    <line x1="50" y1="50" x2="90" y2="70" stroke="rgba(255,255,255,0.05)" strokeWidth="1"/>
                    <line x1="50" y1="50" x2="50" y2="90" stroke="rgba(255,255,255,0.05)" strokeWidth="1"/>
                    <line x1="50" y1="50" x2="10" y2="70" stroke="rgba(255,255,255,0.05)" strokeWidth="1"/>
                    <line x1="50" y1="50" x2="10" y2="30" stroke="rgba(255,255,255,0.05)" strokeWidth="1"/>

                    {/* Data Polygon */}
                    <polygon 
                       points="50,16 76,37 78,66 50,74 26,62 20,40" 
                       fill="rgba(254,180,123,0.3)" 
                       stroke="#feb47b" 
                       strokeWidth="2"
                       className="drop-shadow-[0_0_8px_rgba(254,180,123,1)]"
                    />
                    
                    {/* Data Points */}
                    <circle cx="50" cy="16" r="2.5" fill="#fff" />
                    <circle cx="76" cy="37" r="2.5" fill="#fff" />
                    <circle cx="78" cy="66" r="2.5" fill="#fff" />
                    <circle cx="50" cy="74" r="2.5" fill="#fff" />
                    <circle cx="26" cy="62" r="2.5" fill="#fff" />
                    <circle cx="20" cy="40" r="2.5" fill="#fff" />

                    {/* Labels */}
                    <text x="50" y="5" fill="rgba(255,255,255,0.6)" fontSize="4" textAnchor="middle" fontWeight="bold">Backend</text>
                    <text x="96" y="30" fill="rgba(255,255,255,0.6)" fontSize="4" textAnchor="start" fontWeight="bold">System</text>
                    <text x="95" y="72" fill="rgba(255,255,255,0.6)" fontSize="4" textAnchor="start" fontWeight="bold">Database</text>
                    <text x="50" y="96" fill="rgba(255,255,255,0.6)" fontSize="4" textAnchor="middle" fontWeight="bold">Security</text>
                    <text x="5" y="72" fill="rgba(255,255,255,0.6)" fontSize="4" textAnchor="end" fontWeight="bold">DevOps</text>
                    <text x="4" y="30" fill="rgba(255,255,255,0.6)" fontSize="4" textAnchor="end" fontWeight="bold">Frontend</text>
                 </svg>
              </div>
           </div>

           {/* CV Generator Area */}
           <div className="glass p-6 rounded-3xl border border-[#feb47b]/20 bg-gradient-to-br from-[#5D1636]/40 to-black/40 backdrop-blur-xl">
              <div className="flex items-center gap-4 mb-4">
                 <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#feb47b] to-[#ff7e5f] flex items-center justify-center text-[#5D1636] shadow-lg">
                    <FileText size={20} />
                 </div>
                 <div>
                    <h4 className="font-bold">AI Resume Builder</h4>
                    <p className="text-xs text-white/50">Export PDF Standar Industri</p>
                 </div>
              </div>

              {!cvData ? (
                 <Button 
                   onClick={handleGenerateCV}
                   disabled={isGeneratingCV}
                   className="w-full h-12 rounded-xl bg-white hover:bg-white/90 text-[#0a0514] font-black uppercase tracking-widest text-xs transition-all mt-2"
                 >
                    {isGeneratingCV ? <span className="animate-pulse">Menyiapkan Berkas...</span> : "Generate CV"}
                 </Button>
              ) : (
                 <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="mt-4 pt-4 border-t border-white/10 space-y-4">
                    <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-xl flex items-center gap-3">
                       <CheckCircle2 className="text-emerald-400" size={20} />
                       <div className="text-sm font-bold text-emerald-200">CV Siap Diunduh!</div>
                    </div>
                    <p className="text-xs text-white/70">Role: <span className="font-black text-[#feb47b]">{cvData.recommendedRole}</span></p>
                    <Button className="w-full h-12 rounded-xl bg-[#5D1636] hover:bg-[#8A2150] text-[#feb47b] font-black uppercase tracking-widest text-xs border border-[#feb47b]/30">
                       <Download size={16} className="mr-2" /> Download PDF
                    </Button>
                 </motion.div>
              )}
           </div>
        </div>

        {/* Right Column (60%): Galleries */}
        <div className="w-full lg:w-[60%] flex flex-col gap-6">
           
           {/* Achievement Gallery */}
           <div className="glass p-8 rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl">
              <div className="flex justify-between items-center mb-6">
                 <h3 className="font-bold text-sm tracking-widest uppercase text-white/70 flex items-center gap-2">
                    <Trophy size={16} /> Etalase Pencapaian
                 </h3>
                 <span className="text-[#feb47b] text-xs font-bold bg-[#feb47b]/10 px-3 py-1 rounded-full">3 Prestasi Buka</span>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                 {[
                    { id: 1, title: 'Network Foundation', icon: <Shield size={24} className="text-emerald-400" />, locked: false },
                    { id: 2, title: 'Docker Master', icon: <Award size={24} className="text-blue-400" />, locked: false },
                    { id: 3, title: 'Fast Learner', icon: <Zap size={24} className="text-amber-400" />, locked: false },
                    { id: 4, title: 'AWS Architect', icon: <Shield size={24} className="text-white/20" />, locked: true },
                    { id: 5, title: 'Security Pro', icon: <Shield size={24} className="text-white/20" />, locked: true },
                 ].map(badge => (
                    <div key={badge.id} className={cn(
                       "aspect-[3/4] rounded-2xl border flex flex-col items-center justify-center p-4 text-center transition-all",
                       badge.locked 
                          ? "bg-white/5 border-white/5 opacity-50 grayscale hover:grayscale-0 hover:opacity-100" 
                          : "bg-gradient-to-b from-white/10 to-transparent border-white/20 shadow-lg hover:-translate-y-1 hover:shadow-xl hover:border-white/40"
                    )}>
                       <div className={cn(
                          "w-12 h-12 mb-4 rounded-xl flex items-center justify-center shadow-inner",
                          badge.locked ? "bg-black/40" : "bg-black/40 border border-white/10"
                       )}>
                          {badge.icon}
                       </div>
                       <h4 className="font-bold text-xs uppercase tracking-wider mb-2">{badge.title}</h4>
                       {!badge.locked && <p className="text-[9px] text-white/50 bg-black/40 px-2 py-0.5 rounded-full">Unlocked</p>}
                    </div>
                 ))}
                 
              </div>
           </div>

           {/* Recent Activity / Timeline */}
           <div className="glass p-8 rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl flex-1">
              <h3 className="font-bold text-sm tracking-widest uppercase text-white/70 mb-8 flex items-center gap-2">
                 <Zap size={16} /> Aktivitas Terakhir
              </h3>

              <div className="space-y-6 relative before:absolute before:inset-0 before:ml-[19px] before:h-full before:w-0.5 before:bg-white/10">
                 <div className="relative flex gap-6 group">
                    <div className="w-10 h-10 rounded-full bg-indigo-500/20 border border-indigo-500/50 flex items-center justify-center shrink-0 z-10 shadow-lg group-hover:bg-indigo-500 transition-colors">
                       <CheckCircle2 size={16} className="text-indigo-400 group-hover:text-white" />
                    </div>
                    <div className="pt-2">
                       <p className="font-bold text-sm leading-none flex items-center gap-2">
                          Menyelesaikan Evaluasi Proyek
                          <span className="text-[10px] bg-white/10 px-2 py-0.5 rounded-md text-white/50">2 Hari lalu</span>
                       </p>
                       <p className="text-white/60 text-xs mt-2 leading-relaxed">AI Mentor memberikan skor 92 pada E-Commerce Microservices.</p>
                    </div>
                 </div>

                 <div className="relative flex gap-6 group">
                    <div className="w-10 h-10 rounded-full bg-emerald-500/20 border border-emerald-500/50 flex items-center justify-center shrink-0 z-10 shadow-lg group-hover:bg-emerald-500 transition-colors">
                       <Award size={16} className="text-emerald-400 group-hover:text-white" />
                    </div>
                    <div className="pt-2">
                       <p className="font-bold text-sm leading-none flex items-center gap-2">
                          Mendapatkan Badge "Docker Master"
                          <span className="text-[10px] bg-white/10 px-2 py-0.5 rounded-md text-white/50">4 Hari lalu</span>
                       </p>
                       <p className="text-white/60 text-xs mt-2 leading-relaxed">Berhasil men-deploy 5 container orchestration secara bertahap.</p>
                    </div>
                 </div>

                 <div className="relative flex gap-6 group">
                    <div className="w-10 h-10 rounded-full bg-amber-500/20 border border-amber-500/50 flex items-center justify-center shrink-0 z-10 shadow-lg group-hover:bg-amber-500 transition-colors">
                       <Star size={16} className="text-amber-400 group-hover:text-[#0a0514]" />
                    </div>
                    <div className="pt-2">
                       <p className="font-bold text-sm leading-none flex items-center gap-2">
                          Menyelesaikan Skill Path Assessment
                          <span className="text-[10px] bg-white/10 px-2 py-0.5 rounded-md text-white/50">1 Minggu lalu</span>
                       </p>
                       <p className="text-white/60 text-xs mt-2 leading-relaxed">Sistem mendeteksi potensimu kuat di Backend Logic dan Infrastructure.</p>
                    </div>
                 </div>
              </div>
              
              <Button variant="ghost" className="w-full mt-6 text-xs uppercase tracking-widest font-bold text-white/40 hover:text-white">
                 Muat Lebih Banyak
              </Button>
           </div>
           
        </div>
      </main>
    </div>
  );
}
